# Generated by Django 3.0.5 on 2020-11-25 05:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='', regex='(\n    (\\d{2}|\\(\\d{2}\\)|\\d{3}|\\(\\d{3}\\))?      # 지역번호 : 2자리 또는 3자리, () 포함, 0번또는 1번  \n    (|-|\\.)?                                # 구분자 : 하이푼 또는 . 0번 또는 1번  \n    (\\d{3}|\\d{4})                           # 3자리 또는 4자리 숫자  \n    (\\s|-|\\.)                               # 구분자  \n    (\\d{4})                                 # 4자리 숫자  \n    )')])),
                ('email', models.CharField(blank=True, max_length=200, validators=[django.core.validators.RegexValidator(message='', regex='(  \n    ([a-zA-Z0-9._%+-]+)      # 사용자명\n    @                        # @\n    ([a-zA-Z0-9.-]+)         # 도메인 이름\n    (\\.[a-zA-Z]{2,4})        # 최상위 도메인\n    )')])),
                ('contents', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='mainphoto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
